export {default as Login} from './Login'
export{default as Task} from './Task'
export {default as Profile} from './Profile'
export {default as AddTask} from './AddTask'
export {default as EditTask} from './EditTask'
export {default as EditProfile} from './EditProfile'
export {default as SignUp} from './SignUp'
